backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "index.html"
        label: "Homepage Content"
        name: "homepage"
        fields:
          - label: "Tagline"
            name: "tagline"
            widget: "string"

  - name: "contact"
    label: "Contact Page"
    files:
      - file: "contact.html"
        label: "Contact Info"
        name: "contact"
        fields:
          - label: "Phone"
            name: "phone"
            widget: "string"
          - label: "Email"
            name: "email"
            widget: "string"
          - label: "Address"
            name: "address"
            widget: "string"
